### ISSUE TITLE
Problem with Ion-nav-bar Ionic Framework

### ISSUE THREAD

**Issue by omateuscastro** [ariadnaGomez/ng-walkthrough#1]
The focus is not working, when I try put it in an element inside a Ionic Navigation Bar Ion-Nav-Bar or inside a Ionic Header Bar (ion-header-bar).

**Comment by ariadnaGomez** [comment]
Test the new fix. 
You need to specify that you want to focus an element inside ion-header-bar by setting param header-bar to true. Let me know if it works.

**Comment by omateuscastro** [comment]
Thank You! Its work perfectly.
