### ISSUE TITLE
Problem with ion-nav-buttons Ionic Framework

### ISSUE THREAD

**Issue by omateuscastro** [ariadnaGomez/ng-walkthrough#3]
In First place, congratulations by the excelent job.

I'm having a problem, the focus is not working, when I try put it in an Ionic-Nav-Button (ion-nav-buttons) inside an Ionic Navigation Bar (Ion-Nav-Bar).

**Comment by phyr0s** [comment]
Fixed in https://github.com/ariadnaGomez/ng-walkthrough/issues/1
